site_name: Arc Inventory Documentation
site_description: 'Documentation for Arc Inventory'
site_author: 'Puny Human'
docs_dir: docs/
repo_name: 'RoyAwesome/doctemplate'
repo_url: 'https://royawesome.github.io/doctemplate/'
copyright : Copyright &copy; 2020-2021 Puny Human
extra_css:
  - stylesheets/extra.css
nav:
    - Home: index.md
    - "Initial Setup": initialsetup.md
    - "Concepts":
        - "High Level": "concepts/highlevel.md"
        - "Inventory": "concepts/inventory.md"
        - "Item Stacks": "concepts/itemstack.md"
        - "Item Generators": "concepts/generators.md"
        - "User Interface": "concepts/ui.md"
    - Tutorials:
      - "Simple FPS": "tutorials/simplefps.md"
      - "Containers": "tutorials/containers.md"
    - Integrations:
      - "MoveIt": "integrations/moveit.md"
    - "Useful Resources": usefulresources.md
    - Changelogs:
      - 'changelogs/1.2.2.113.md'
      - 'changelogs/1.2.1.106.md'
      - 'changelogs/1.2.0.md'
theme:
  name: 'material'
  palette:
    scheme: slate
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - pymdownx.tabbed
