site_name: Arc Inventory Documentation
site_description: 'Documentation for Arc Inventory'
site_author: 'Puny Human'
docs_dir: docs/
repo_name: 'RoyAwesome/doctemplate'
repo_url: 'https://royawesome.github.io/doctemplate/'
copyright : Copyright &copy; 2020-2021 Puny Human
nav:
    - Home: index.md
    - SimpleTutorial: simpletutorial.md
    - Abbtest: abbtest.md
theme:
  name: 'material'
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
