site_name: Arc Inventory Documentation
site_description: 'Documentation for Arc Inventory'
site_author: 'Puny Human'
docs_dir: docs/
repo_name: 'RoyAwesome/doctemplate'
repo_url: 'https://royawesome.github.io/doctemplate/'
nav:
    - Home: index.md
theme:
  name: 'material'
